#!/bin/bash 

backup_date=$(date +'%m/%d/%y %h:%m:%s')

df -H | awk '{print $5 "" $1}' | while read output; 
do
 usage=$(echo $output | awk '{print $1}' | cut -d'%' -f1)
 file_system=$(echo $output | awk '{print $2}') 
 
 if [ $usage -ge 90] 
 then 
  echo "CRITICAL for $file_system on $backup_date" 
 fi 
done